import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// AIAvatarProfilePics — generated by AppFactoryKit appgen from niche "ai-avatar".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum AIAvatarProfilePicsFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "AIAvatarProfilePics",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "wand.and.stars",
                          title: "AIAvatarProfilePics",
                          message: "Stylized AI avatars from selfies."),
                    .init(systemImage: "photo.on.rectangle.angled",
                          title: "Go Pro",
                          message: "More packs/styles, HD, no watermark.")
                ],
                presentsPaywallOnFinish: true,
                accent: .purple
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock AIAvatarProfilePics Pro",
                subheadline: "More packs/styles, HD, no watermark.",
                benefits: [
                    .init(systemImage: "infinity", title: "More packs/styles"),
                    .init(systemImage: "bolt.fill", title: "HD"),
                    .init(systemImage: "nosign", title: "No watermark")
                ],
                productIDs: ["ai-avatar_yearly", "ai-avatar_weekly"],
                highlightedProductID: "ai-avatar_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .purple, heroSystemImage: "wand.and.stars")
            )
        )
        return AppFactory(config)
    }
}

@main
struct AIAvatarProfilePicsApp: App {
    @StateObject private var factory = AIAvatarProfilePicsFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.purple)
        }
    }
}
